### ISSUE TITLE
Remove simple relationship?

### ISSUE THREAD

**Issue by JoeThielen** [graphaware/neo4j-php-ogm#104]
I can't figure out how to remove a simple relationship.  I see in the docs how to remove a RelationshipEntity if it's provided for in the model, like it is with rating (Rating has it's own class).  But what about the movie dataset.  How do you do something like remove Tom Hanks from Cast Away if all you have are the Person and Movie classes?  I've looked in the unit tests, and all I can see are the RelationshipEntity removal tests.  

I've tried to do it manually by using the removeActor and/or removeMovie methods, but when I flush it either doesn't do anything, or I get an error like:

> Error: Call to undefined method neo4j_ogm_proxy_GraphAware_Neo4j_OGM_Tests_Integration_Models_MoviesDemo_Person::removeMovie()

I've also tried removeElement on the arrayCollection.  That seems to work for the current in-memory objects, but flushing won't make it persist.  

Can you provide a unit test in tests/Integration/MovieDatasetTest.php which would demonstrate this?

Thank you so much!

**Comment by theUm** [comment]
It seems I'm having this bug too. Here`s my code:
![persist_remove_relationship](https://cloud.githubusercontent.com/assets/3176889/23801412/c281ae0c-05b8-11e7-937c-d33c3ad9f3ae.png)
result of execution:
![persist_remove_relationship_result](https://cloud.githubusercontent.com/assets/3176889/23801432/ce2216ac-05b8-11e7-811a-c6086f62d8e4.png)

After some digging in UnitOfWork code, by following execution path of `UOW->persist($node)` call in my case I can't find code responsible for removing the simple relationship. UOW's method `->persistRelationship(...)` can only create relationsips via manipulations on `$this->relationshipsScheduledForCreated[]`

BTW here's my mappion of the ObjectNode:
![persist_remove_relationship_mapping](https://cloud.githubusercontent.com/assets/3176889/23801851/3b2847ac-05ba-11e7-847c-d3b48e9b4da3.png)

**Comment by sts85** [comment]
I have the same problem. It used to work by just removing the element from the ArrayCollection, but with RC1 this does not work anymore.

**Comment by ikwattro** [comment]
Yes I need to fix that. @sts85 would you be able to send me an email to christophe @ graphaware dot com. I will send an e-mail with some info about the ogm I cannot write publicly yet.

**Comment by vladrolandomihai** [comment]
I encountered the same problem. Was just about to make an issue.

```php
$john = $repo->findOneBy(['name' => 'John']);
$jane = $repo->findOneBy(['name' => 'Jane']);
$john->removeFriend($jane);
//$em->persist($john);
$em->flush();
```

Jane is removed from the in-memory list of John's friends. However, the db is not updated.
Are you actively maintaining this project? I would like to use it in an important project of my own :D.

**Comment by ikwattro** [comment]
Fixed by #108

**Comment by JoeThielen** [comment]
I am still having this issue when there is not a collection involved.  For example, in tests/Integration/EntityWithSimpleRelationshipTest.php 

If I modify the testPersonIsCreatedWithCar() method to look like this:

```
    public function testPersonIsCreatedWithCar()
    {
        $person = new Person('Mike');
        $car = new Car('Bugatti', $person);
        $person->setCar($car);
        $this->em->persist($person);
        $this->em->flush();

        $result = $this->client->run('MATCH (n:Person {name:"Mike"})-[:OWNS]->(c:Car {model:"Bugatti"}) RETURN n, c');
        $this->assertSame(1, $result->size());
        //exit;

        $this->em->clear();

        $bugatti = $this->em->getRepository(Car::class)->findOneBy(array('model' => 'Bugatti'));
        //echo "\n|" . print_r($bugatti->getModel(),1 ) . "|\n";
        $mike = $this->em->getRepository(Person::class)->findOneBy(array('name' => 'Mike'));
        //echo "\n|" . print_r($mike->getName(),1 ) . "|\n";

        $mike->setCar(null);
        $bugatti->setOwner(null);
        $this->em->flush();

        $result = $this->client->run('MATCH (n:Person {name:"Mike"})-[:OWNS]->(c:Car {model:"Bugatti"}) RETURN n, c');
        $this->assertSame(0, $result->size());
        //exit;

    }

```

I also have to modify tests/Integration/Models/EntityWithSimpleRelationship/Car.php to add the setOwner() method:

```
    /**
     * @param string $owner
     */
    public function setOwner($owner)
    {
        $this->owner = $owner;
    }

```

The new test will fail, and if I uncomment the exit and pull up the graph manually, the relationship still exists.

In my project I have a similar issue, but it's a mixed setup where, just for example, an owner may have a collection of cars, but a car may only have one owner, and I'm not able to get the relationship to be removed.  It works in the entity manager memory, but doesn't remove the relationship in the graph DB.

**Comment by ikwattro** [comment]
Thanks @JoeThielen , looking at it now
